# docker-compose.yml
version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - vw_data:/data
      - vw_config:/config
    environment:
      - DOMAIN=https://vault.tondomaine.com
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DATABASE_URL=sqlite:///data/db.sqlite3
      - SENDS_ALLOWED=true
      - WEBSOCKET_ENABLED=true
    ports:
      - "8080:80"
    networks:
      - vaultwarden_net

  backup_service:
    image: alpine:latest
    container_name: vw_backup
    restart: unless-stopped
    volumes:
      - vw_data:/source:ro
      - ./scripts:/scripts:ro
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}
    command: crond -f -d 8
    depends_on:
      - vaultwarden

volumes:
  vw_data:
    driver: local
  vw_config:
    driver: local

networks:
  vaultwarden_net:
    driver: bridge
